sem2/1 homework/messenger/community/urls.py
from django.urls import path

from community import views

app_name = "group"

urlpatterns = [
    path('<int:id>', views.page_detail, name='group')
]

sem2/1 homework/messenger/main/urls.py
from django.contrib import admin
from django.urls import path, include

from main import views

urlpatterns = [
    path("im/", views.show_message, name='show_message')
]

sem2/1 homework/messenger/messenger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('messages/', include("msgs.urls", namespace="message")),
    path('group/', include("community.urls", namespace="group")),
    path('', include("profile_page.urls", namespace="people")),
]

sem2/1 homework/messenger/profile_page/urls.py
from django.contrib.staticfiles.urls import static
from django.urls import path
from django.views.generic.base import TemplateView

from messenger.settings import MEDIA_URL, MEDIA_ROOT
from profile_page import views

app_name = "people"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('people/<int:id>', views.page_detail, name='profile_page'),
    path('logout/', views.logout, name='logout'),
    path('add/<int:id>', views.add_friend, name="add_friend"),
    path('people/admin', views.admin_view, name="admin_view"),
    path('post/<int:id>/ajax', views.ajax_like, name="ajax_like"),
    path('', TemplateView.as_view(template_name="profile_page/welcome.html"), name="welcome")
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

sem2/1 homework/messenger/profile_page/models.py
from django.contrib.auth.models import User
from django.db import models

from page.models import Page, VerificationMixin, DocumentsMixin


class ProfilePage(Page):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subscribe_to = models.ManyToManyField('self', related_name="subscribe_to")
    subscribe_to_groups = models.ManyToManyField('community.Group', related_name="subscribe_to_group")

sem2/1 homework/messenger/profile_page/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators
from django.forms import modelform_factory

from walls.models import Article


class LoginForm(forms.ModelForm):
    password = forms.CharField(min_length=8, max_length=20, widget=forms.PasswordInput)
    email = forms.CharField(validators=[validators.validate_email])

    class Meta:
        model = User
        fields = ["email", "password"]


PostForm = modelform_factory(Article, fields=["text", "image"])

sem2/1 homework/messenger/profile_page/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q
from django.http.response import HttpResponse
from django.shortcuts import render, redirect

from django.urls import reverse

from msgs.models import Msg
from profile_page.forms import LoginForm, PostForm
from profile_page.models import ProfilePage
from walls.models import Article


@login_required
def page_detail(request, id):
    page = ProfilePage.objects.get(pk=id)
    avatar = page.page_picture.order_by("-date")[0]
    q1 = Q(subscribes=page)
    q2 = Q(subscribe_to=page)
    q3 = q1 & q2
    q4 = q1 & ~q2
    friends = ProfilePage.objects.filter(q3)
    subs = ProfilePage.objects.filter(q4)
    wall = page.walls.articles.order_by("-date")
    groups = page.subscribe_to_groups.all()
    form = PostForm()
    if request.POST:
        f = PostForm(request.POST, request.FILES)
        article = f.save(commit=False)
        article.who_posted = page
        article.save()
        page.walls.articles.add(article)
        return redirect(reverse("people:profile_page", args=(id, )))

    return render(request, 'profile_page/profile_page.html',
                  {
                      'user': request.user,
                      'page': page,
                      'avatar': avatar,
                      'subs': subs,
                      'friends': friends,
                      'wall': wall,
                      'groups': groups,
                      'form': form
                  })


def login(request):
    if request.user.is_authenticated:
        return redirect(reverse("people:profile_page", args=(request.user.id, )))
    form = LoginForm()
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            username = ProfilePage.objects.get(user__email=email).user.username
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                if "next" in request.GET:
                    return redirect(request.GET["next"])
                return redirect(reverse("people:profile_page", args=(request.user.id, )))
    return render(request, 'profile_page/login.html', {"form": form})


@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse("people:login"))


@login_required
def add_friend(request, id):
    page_friend = ProfilePage.objects.get(id=id)
    page = ProfilePage.objects.get(id=request.user.id)
    page.subscribe_to.add(page_friend)
    page_friend.subscribes.add(page)
    page_friend.save()
    page.save()
    return redirect(reverse("people:profile_page", args=(id, )))


@permission_required('admin')
def admin_view(request):
    msgs = Msg.objects.values_list("text", "date")
    articles = Article.objects.filter(like__gt=3)
    return render(request, "profile_page/admin.html", {
        "articles": articles,
        "msgs": msgs
    })


@permission_required('admin')
def ajax_like(request, id):
    article = Article.objects.get(pk=id)
    count_like = article.like + 1
    article.like = count_like
    article.save()
    return HttpResponse(count_like)

sem2/1 homework/messenger/profile_page/templates/profile_page/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Админ<br>
Посты с более 3 лайками <br>
{% for article in articles %}
    {{ article.text }}<br>
{% endfor %}
<br>
Сообщения пользователей <br>
{% for msg in msgs %}
    {{ msg.0 }}<br>
    {{ msg.1 }}<br>
{% endfor %}
</body>
</html>

sem2/1 homework/messenger/profile_page/templates/profile_page/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>VK</title>
</head>
<body>
    <form method="post"> {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Войти">
    </form>
</body>
</html>

sem2/1 homework/messenger/profile_page/templates/profile_page/profile_page.html
{% extends "base.html" %}
{% block name %}
    {{ page.user.first_name }}
    {{ page.user.last_name }}<br>
    {{ page.status }}
{% endblock %}
{% block table %}
    <table>
        <tr align="center">
            <td>
                {{ friends.count }}
            </td>
            <td>
                {{ subs.count }}
            </td>
        </tr>
        <tr>
            <td>
                Друзей
            </td>
            <td>
                Подписчиков
            </td>
        </tr>
    </table>
{% endblock %}
{% block action %}
    {% if user.id != page.id %}
        {% if user.id not in friends.id %}
            <a href="{% url "people:add_friend" page.id %}"><button>Добавить в друзья</button></a><br>
        {% endif %}
    {% endif %}
{% endblock %}
{% block leftmain %}
    <div class="friends">
        {% for friend in friends|slice:":6" %}
            <a href="{% url 'people:profile_page' friend.pk %}">
                <div class="friend">
                    <img src="" alt="{{ friend.page_picture.order_by.first }}">
                    {{ friend.user.first_name }} <br>
                    {{ friend.user.last_name }}
                </div>
            </a>
        {% endfor %}
    </div>
    <div class="groups">
        {% for group in groups|slice:":6" %}
            <a href="{% url 'group:group' group.pk %}">
                <div class="group">
                    <img src="" alt="{{ group.page_picture.name }}">
                    {{ group.title }}
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}
{% block wall %}
    {% include "wall_include.html" %}
{% endblock %}

sem2/1 homework/messenger/profile_page/templates/profile_page/profile_page1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>VK</title>
    <style>
        header{
            background: lawngreen;
            height: 50px;
        }
        .menu{
            float: left;
            background: #cccccc;
            width: 200px;
            height: 700px;
            margin-left: 100px;
        }
        .main{
            margin-left: 300px;
            background: aquamarine;
            width: 700px;
            height: 700px;
        }
        .avatar{
            float: left;
            width: 200px;
            height: 200px;
            background: antiquewhite;
        }
        .name{
            height: 100px;
        }
        .table{
            height: 100px;
        }
        .friends {
            background: azure;
            width: 300px;
            height: 300px;
        }
        .friend {
            background: gray;
            height: 140px;
            width: 90px;
            margin: 5px;
        }
        .walls {
            float: right;
            width: 400px;
            background: #cccccc;
        }
        .article {
            margin: 10px;
        }
        .groups {
            background: azure;
            width: 300px;
            height: 300px;
        }
        .group {
            background: gray;
            height: 140px;
            width: 90px;
            margin: 5px;
        }
        .leftmain {
            float: left;
        }
    </style>
</head>
    <body>
        <header>

        </header>
        <div>
            <div class="menu">
                <ul>
                    <a href="">
                        <li>
                            Моя страница
                        </li>
                    </a>
                    <li>
                        Мои сообщения
                    </li>
                    <li>
                        Мои фотографии
                    </li>
                    <li>
                        Мои аудизаписи
                    </li>
                </ul>
            </div>
            <div class="main">
                <div class="avatar">
                    <img src="" alt="{{ avatar.img.name }}">
                </div>
                <div class="name">
                    {{ page.user.first_name }}
                    {{ page.user.last_name }}<br>
                    {{ page.status }}
                </div>
                <div class="table">
                    <table>
                        <tr align="center">
                            <td>
                                {{ friends.count }}
                            </td>
                            <td>
                                {{ subs.count }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Друзей
                            </td>
                            <td>
                                Подписчиков
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="leftmain">
                    <div class="friends">
                        {% for friend in friends %}
                            <a href="/people/{{ friend.pk }}">
                                <div class="friend">
                                    <img src="" alt="{{ friend.page_picture.order_by.first }}">
                                    {{ friend.user.first_name }} <br>
                                    {{ friend.user.last_name }}
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                    <div class="groups">
                        {% for group in groups %}
                            <a href="/group/{{ group.pk }}">
                                <div class="group">
                                    <img src="" alt="{{ group.page_picture.name }}">
                                    {{ group.title }}
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                </div>
                <div class="walls">
                    Стена
                    {% for article in wall %}
                        <div class="article">
                            <a href="/people/{{ article.who_posted.pk }}">
                                {{ article.who_posted.user.first_name }}
                                {{ article.who_posted.user.last_name }}<br>
                            </a>
                            {{ article.text }}<br>
                            {{ article.date }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </body>
</html>

sem2/1 homework/messenger/profile_page/templates/profile_page/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form>
        {{ form.as_p }}
    </form>
</body>
</html>

sem2/1 homework/messenger/profile_page/templates/profile_page/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>VK</title>
</head>
<body>
    <h1>Welcome</h1>
</body>
</html>