sem2/1 homework/messenger/main/urls.py
from django.contrib import admin
from django.urls import path, include

from main import views

urlpatterns = [
    path("im/", views.show_message, name='show_message')
]

sem2/1 homework/messenger/messenger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('messages/', include("msgs.urls", namespace="message")),
    path('group/', include("community.urls", namespace="group")),
    path('', include("profile_page.urls", namespace="people")),
]

sem2/1 homework/messenger/msgs/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from msgs import views

app_name = "message"

urlpatterns = [
    path('im/', login_required(views.MyListView.as_view()), name='im'),
    path('im/<int:id>', login_required(views.CreateMsg.as_view()), name='detail'),
]

sem2/1 homework/messenger/msgs/models.py
# from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now
from messenger.settings import CUT_MSG_TEXT_LENGTH


# Create your models here.


class Msg(models.Model):
    user_send = models.ForeignKey('auth.User', related_name="send", on_delete=models.PROTECT)
    user_src = models.ForeignKey('auth.User', related_name="src", on_delete=models.PROTECT)
    text = models.TextField()
    date = models.DateTimeField(default=now)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return "От:%s, Кому:%s, Текст:%s" % (self.user_send.first_name, self.user_src.first_name, self.text)

    def cut(self):
        return self.text[:CUT_MSG_TEXT_LENGTH] + "..."

sem2/1 homework/messenger/msgs/forms.py
from msgs.models import Msg
from django import forms


class MsgForm(forms.ModelForm):
    class Meta:
        model = Msg
        fields = ["text"]

sem2/1 homework/messenger/msgs/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import F
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic.list import ListView

from msgs.forms import MsgForm
from msgs.models import Msg


class MyListView(ListView):
    template_name = "msgs/im.html"
    model = Msg

    def get_context_data(self, **kwargs):
        context = super(MyListView, self).get_context_data(**kwargs)
        context["msgs"] = Msg.objects.filter(user_src=self.request.user) \
            .exclude(user_src=F("user_send")).order_by("-date")
        return context


class CreateMsg(CreateView):
    model = Msg
    form_class = MsgForm
    template_name = "msgs/msg.html"
    success_url = reverse_lazy("message:im")

    def get(self, request, *args, **kwargs):
        id = kwargs.get("id")
        msg = Msg.objects.get(pk=id)
        context = {'form': MsgForm, 'msg': msg}
        request.session["user_send"] = msg.user_send.pk
        return render(request, 'msgs/msg.html', context)

    def form_valid(self, form):
        msg = form.save(commit=False)
        msg.user_send = self.request.user
        msg.user_src = User.objects.get(pk=self.request.session["user_send"])
        msg.save()
        return HttpResponseRedirect(self.success_url)

sem2/1 homework/messenger/msgs/templates/msgs/im.html
{% extends "base.html" %}
{% block msgs %}
    <h2>My Messages</h2>
    <table border=1 width="80%">
        {% for m in msgs %}
            {% if m.is_read %}
                <tr>
            {% else %}
                <tr bgcolor="#00ff00">
            {% endif %}
                <td> from: {{ m.user_send.username }} <br>
                </td>
                <td> <a href="{% url "message:detail" m.id %}">{{ m.cut }}</a> </td>
                <td> date: {{ m.date }} </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

sem2/1 homework/messenger/msgs/templates/msgs/msg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>VK</title>
    <style>
        .main_content {
            background-color: #ccc;
            margin-left: 20%;
            width: 60%;
        }
        .msg {

        }
        .form {
            margin-left: 35%;
        }
        
    </style>
</head>
<body>
<div class="main_content">
    <a href="{% url 'message:im' %}"><button>Назад</button></a>
    <p>
        От: {{ msg.user_send.first_name }} {{ msg.user_send.last_name }}
    </p>
    <p>
        <div class="msg">
            {{ msg.text }}
        </div>
    </p>
    <p>
        Дата: {{ msg.date }}
    </p>
</div>
    <form method="post" class="form"> {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Ответить">
    </form>
</body>
</html>