sem2/1 homework/messenger/main/urls.py
from django.contrib import admin
from django.urls import path, include

from main import views

urlpatterns = [
    path("im/", views.show_message, name='show_message')
]

sem2/1 homework/messenger/messenger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('messages/', include("msgs.urls", namespace="message")),
    path('group/', include("community.urls", namespace="group")),
    path('', include("profile_page.urls", namespace="people")),
]

sem2/1 homework/messenger/msgs/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from msgs import views

app_name = "message"

urlpatterns = [
    path('im/', login_required(views.MyListView.as_view()), name='im'),
    path('im/<int:id>', login_required(views.CreateMsg.as_view()), name='detail'),
]

sem2/1 homework/messenger/profile_page/urls.py
from django.contrib.staticfiles.urls import static
from django.urls import path
from django.views.generic.base import TemplateView

from messenger.settings import MEDIA_URL, MEDIA_ROOT
from profile_page import views

app_name = "people"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('people/<int:id>', views.page_detail, name='profile_page'),
    path('logout/', views.logout, name='logout'),
    path('add/<int:id>', views.add_friend, name="add_friend"),
    path('people/admin', views.admin_view, name="admin_view"),
    path('post/<int:id>/ajax', views.ajax_like, name="ajax_like"),
    path('', TemplateView.as_view(template_name="profile_page/welcome.html"), name="welcome")
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

sem2/1 homework/messenger/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>VK</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
    <body>
        <header>
            {{ user.first_name }} {{ user.last_name }}
            <a href="{% url "people:logout" %}"><button>Выйти</button></a>
        </header>
        <div>
            <div class="menu">
                <ul>
                    <a href="{% url 'people:profile_page' user.id %}">
                        <li>
                            Моя страница
                        </li>
                    </a>
                    <a href="{% url 'message:im' %}">
                        <li>
                            Мои сообщения
                        </li>
                    </a>
                </ul>
            </div>
            <div class="main">
                <div class="avatar">
                    <img src="" alt="{{ avatar.img.name }}">
                </div>
                <div class="name">
                    {% block name %}
                    {% endblock %}
                </div>
                <div class="table">
                    {% block table %}
                    {% endblock %}
                </div>
                <div>
                    {% block action %}
                    {% endblock %}
                </div>
                <div class="rightmain">
                    {% block main %}
                    {% endblock %}
                </div>
                <div class="leftmain">
                    {% block leftmain %}
                    {% endblock %}
                </div>
                {% block msgs %}
                {% endblock %}
                {% block wall %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

sem2/1 homework/messenger/templates/main_content_incl.html
<div class="main">
        <div class="avatar">
            <img src="" alt="{{ avatar.img.name }}">
        </div>
        <div class="name">
            {% block name %}
            {% endblock %}
        </div>
        <div class="table">
            {% block table %}
            {% endblock %}
        </div>
        <div class="rightmain">
            {% block rightmain %}
            {% endblock %}
        </div>
        <div class="leftmain">
            {% block leftmain %}
            {% endblock %}
        </div>
</div>

sem2/1 homework/messenger/templates/wall_include.html
<div class="walls">
    Стена
    <form method="post" enctype="multipart/form-data"> {% csrf_token %}
        {{ form.as_p }}
        Всего символов: <span id="count"></span><br>
        <input type="submit" value="Отправить">
    </form>
    {% for article in wall %}
        <div class="article">
            <a href="{% url "people:profile_page" article.who_posted.pk %}">
                {{ article.who_posted.user.first_name }}
                {{ article.who_posted.user.last_name }}<br>
            </a>
            {{ article.text }}<br>
            {% if article.image %}
                <img src="{{ article.image.url }}" width="50" height="50"> <br>
            {% endif %}
            {{ article.date }}
            <p>
                Likes: <button class="count" data-pk = "{{ article.pk }}">{{ article.like }}</button>
            </p>
        </div>
    {% endfor %}
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var text_area = document.getElementById("id_text");
        text_area.oninput = function () {
            document.getElementById("count").innerHTML = text_area.value.length;
        };
        var buttons = document.getElementsByClassName("count");
        for (var i = 0; i < buttons.length; i++) {
            buttons[i].addEventListener("click", function(e) {
                var id = e.srcElement.dataset.pk;
                $.ajax({
                    url: "/post/" + id + "/ajax",
                    type: 'get',
                    success: function(data) {
                        e.srcElement.innerHTML = data;
                    }
                });
            });
        }
    });
</script>